module.exports = {
  presets: ["module:metro-react-native-babel-preset"],
  plugins: [
    "react-native-web",
    [
      "module-resolver",
      {
        root: ["."],
        extensions: [
          ".ios.ts",
          ".android.ts",
          ".ts",
          ".ios.tsx",
          ".android.tsx",
          ".tsx",
          ".jsx",
          ".js",
          ".json",
        ],
        alias: {
          "^react-native$": "react-native-web",
          Assets: "./src/Assets",
          Images: "./src/Assets/Images",
          Business: "./src/Business",
          Common: "./src/Common",
          Components: "./src/Components",
          Config: "./src/Config",
          Containers: "./src/Containers",
          Fixtures: "./src/Fixtures",
          Hooks: "./src/Hooks",
          Locales: "./src/Locales",
          Models: "./src/Models",
          Navigation: "./src/Navigation",
          Redux: "./src/Redux",
          Actions: "./src/Redux/Actions",
          Reducers: "./src/Redux/Reducers",
          Providers: "./src/Providers",
          Sagas: "./src/Sagas",
          Services: "./src/Services",
          Styles: "./src/Styles",
          Themes: "./src/Themes",
          Transforms: "./src/Transforms",
          Utils: "./src/Utils",
        },
      },
    ],
  ],
};
