export const sharedColors = {
  facebook: "#2B86F1",
  blackOpacity: "rgba(0, 0, 0, 0.3)",
  black: "#000000",
  primary: "#720D5D",
  activePrimary: "#632066",
  inactivePrimary: "#e5e5e5",
  white: "#FFFFFF",
  red: "#FF0000",
  greyBackground: "#F2F2F2",
  greyPrimary: "#7C7C7C",
  bootstrapPrimary: "#0275d8",
  bootstrapSuccess: "#5cb85c",
  bootstrapDanger: "#d9534f",
  bootstrapWarning: "#f0ad4e",
  bootstrapInfo: "#5bc0de",
  bootstrapInverse: "#292b2c",
  primaryInactive: "#beb6ce",
  primaryInactiveOpacity: "rgba(190, 182, 206, 0.12)",
  primaryBorder: "#e0dce6",
  primaryBorderAlt: "#e6e6f2",
  titleItem: "#606060",
  greyItem: "#9C9E9B",
  lightGreyItem: "#888888",
  primaryRed: "#ff4715",
  primaryOrange: "#FF7d38",
  primaryGrey: "#6f6d79",
  primaryText: "#090110",
  primaryGradient: ["#ff4715", "#e30c7c"],
  primaryRedBackground: "rgba(255, 71, 21, 0.06)",
  switchActive: "#9b2d0f",
  darkBackground: "#262331",
  lightBackground: "#f2f2fa",
  darkCard: "#3a374a",
  softLight: "rgba(255, 255, 255, 0.6)",
  darkFooter: "#1a1524",
};

export const lightThemeColors = {
  ...sharedColors,
  statusBarContent: "dark-content",
  primaryTitle: sharedColors.darkBackground,
  primaryTitleOpacity: (opacity = 0.8) => `rgba(38, 35, 49, ${opacity})`,
  tabBackground: sharedColors.white,
  tabInactiveTitle: sharedColors.primaryGrey,
  background: sharedColors.lightBackground,
  inverseBackground: sharedColors.lightBackground,
  backgroundOpacity: "rgba(255, 255, 255, 0.7)",
  inactivePrimary: "#e5e5e5",
  greyBackground: "#F2F2F2",
  greyPrimary: "#7C7C7C",
  titleItem: "#606060",
  greyItem: "#9C9E9B",
  lightGreyItem: "#888888",
  cardBackground: sharedColors.white,
  inverseCardBackground: sharedColors.white,
  programTagBackground: "rgba(255, 71, 21, 0.06)",
  portraitBorder: sharedColors.lightBackground,
  highlightText: sharedColors.primaryRed,
  inactiveText: sharedColors.primaryInactive,
  activeText: sharedColors.primaryRed,
  calendarBorder: sharedColors.primaryRed,
  checkboxBackground: sharedColors.lightBackground,
  timelineItem: sharedColors.white,
  border: sharedColors.primaryInactive,
  error: sharedColors.red,
  errorOpacity: sharedColors.primaryRedBackground,
  buttonBackground: sharedColors.white,
  inputTitle: sharedColors.primaryGrey,
  switchInactive: sharedColors.primaryInactive,
  oldTitle: sharedColors.primaryText,
  text: sharedColors.primaryText,
  divider: sharedColors.primaryBorderAlt,
  dayOff: {
    button: sharedColors.primaryBorderAlt,
    text: sharedColors.primaryInactive,
  },
  payment: {
    discountContainer: "rgba(255, 71, 21, 0.06)",
    discountText: sharedColors.primaryRed,
    originalPrice: sharedColors.primaryText,
  },
  closeText: sharedColors.primaryText,
  footer: {
    background: sharedColors.white,
  },
  tab: {
    line: sharedColors.primaryBorder,
  },
};

export const darkThemeColors = {
  ...sharedColors,
  statusBarContent: "light-content",
  primaryTitle: sharedColors.white,
  primaryTitleOpacity: (opacity = 0.8) => `rgba(38, 35, 49, ${opacity})`,
  tabBackground: sharedColors.darkBackground,
  tabInactiveTitle: sharedColors.primaryInactive,
  background: sharedColors.darkBackground,
  inverseBackground: sharedColors.darkCard,
  backgroundOpacity: "rgba(38, 35, 49, 0.7)",
  inactivePrimary: "#e5e5e5",
  greyBackground: "#F2F2F2",
  greyPrimary: "#7C7C7C",
  titleItem: sharedColors.white,
  greyItem: "#9C9E9B",
  lightGreyItem: "#888888",
  cardBackground: sharedColors.darkCard,
  inverseCardBackground: sharedColors.darkBackground,
  programTagBackground: sharedColors.darkBackground,
  portraitBorder: sharedColors.white,
  highlightText: sharedColors.white,
  inactiveText: sharedColors.white,
  activeText: sharedColors.darkBackground,
  calendarBorder: sharedColors.white,
  checkboxBackground: sharedColors.darkCard,
  timelineItem: sharedColors.primaryText,
  border: sharedColors.darkBackground,
  error: sharedColors.primaryOrange,
  errorOpacity: "rgba(255, 125, 56, 0.11)",
  buttonBackground: "#49455f",
  inputTitle: sharedColors.softLight,
  switchInactive: sharedColors.darkBackground,
  oldTitle: sharedColors.softLight,
  text: sharedColors.white,
  divider: sharedColors.darkFooter,
  dayOff: {
    button: sharedColors.white,
    text: sharedColors.primaryGrey,
  },
  payment: {
    discountContainer: sharedColors.primaryOrange,
    discountText: sharedColors.white,
    originalPrice: sharedColors.white,
  },
  closeText: sharedColors.primaryInactive,
  footer: {
    background: sharedColors.darkFooter,
  },
  tab: {
    line: sharedColors.darkCard,
  },
};
export default lightThemeColors;
